graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: true
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /book
    cors-enabled: true
    cors:
      allowed-methods: GET, HEAD, POST
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    # Sets if asynchronous operations are supported for GraphQL requests. If not specified defaults to true.
    async-mode-enabled: true

# データベース設定．環境に合わせて変えてください
spring:
  datasource:
    sample:
      driverClassName: org.postgresql.Driver
      sqlScriptEncoding: UTF-8
      # pooling
      maxActive: 15
      maxIdle: 10
      minIdle: 5
      initialSize: 2
      # Re-connect
      validationQuery: SELECT 1 FROM DUAL
      testOnBorrow: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 600000
      minEvictableIdleTimeMillis: 600000
      url: jdbc:postgresql://localhost:5432/library
      username: test_user
      password: test
